### Api ping
GET http://localhost:8080/api/v1/ping
Authorization: Bearer 553a11cf-3c0e-4c9b-b5be-8065952a7927

### Get product by barcode
GET http://localhost:8080/api/v1/product/49705696088
Authorization: Bearer 553a11cf-3c0e-4c9b-b5be-8065952a7927

### Creatre product
POST http://localhost:8080/api/v1/product
Content-Type: application/json
Authorization: Bearer 553a11cf-3c0e-4c9b-b5be-8065952a7927

{
  "name": "TEST",
  "upcean": 49705696088,
  "category_id": 463,
  "brand_id": 909
}

### Update product
PUT http://localhost:8080/api/v1/product
Content-Type: application/json
Authorization: Bearer 553a11cf-3c0e-4c9b-b5be-8065952a7927

{
  "id": 5006351,
  "name": "NO_TEST",
  "upcean": 49705696088,
  "category_id": 463,
  "brand_id": 909
}

### Delete product by id
DELETE http://localhost:8080/api/v1/product/5006351
Authorization: Bearer 553a11cf-3c0e-4c9b-b5be-8065952a7927

### Creatre shopping list
POST http://localhost:8080/api/v1/shopping-list
Content-Type: application/json
Authorization: Bearer 553a11cf-3c0e-4c9b-b5be-8065952a7927

{
  "name": "TEST_SHOPPING_LI",
  "account_id": 233575306
}

### Update shopping list
PUT http://localhost:8080/api/v1/shopping-list
Content-Type: application/json
Authorization: Bearer 553a11cf-3c0e-4c9b-b5be-8065952a7927

{
  "id": 1,
  "name": "TEST_SHOPPING_LILI",
  "account_id": 233575306
}